apiVersion: v1
kind: ConfigMap
metadata:
  namespace: openshift-kube-storage-version-migrator-operator
  name: config
data:
  config.yaml: |
    apiVersion: operator.openshift.io/v1
    kind: GenericOperatorConfig
