apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.openshift.io/serving-cert-secret-name: metrics-tls
  labels:
    name: dns-operator
  name: metrics
  namespace: openshift-dns-operator
spec:
  ports:
  - name: metrics
    port: 9393
    targetPort: metrics
  selector:
    name: dns-operator
  type: ClusterIP
