apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: openshift-kube-storage-version-migrator-operator
  name: kube-storage-version-migrator-operator
  labels:
    app: kube-storage-version-migrator-operator
