apiVersion: config.openshift.io/v1
kind: ClusterOperator
metadata:
  name: authentication
  annotations:
    exclude.release.openshift.io/internal-openshift-hosted: "true"
status:
  versions:
  - name: operator
    version: "4.5.4"
  - name: oauth-openshift
    version: "4.5.4_openshift"
