apiVersion: config.openshift.io/v1
kind: ClusterOperator
metadata:
  name: operator-lifecycle-manager
status:
  versions:
    - name: operator
      version: "4.5.4"
---
apiVersion: config.openshift.io/v1
kind: ClusterOperator
metadata:
  name: operator-lifecycle-manager-catalog
status:
  versions:
    - name: operator
      version: "4.5.4"
---
apiVersion: config.openshift.io/v1
kind: ClusterOperator
metadata:
  name: operator-lifecycle-manager-packageserver
status:
  versions:
    - name: operator
      version: "4.5.4"
