apiVersion: v1
kind: Namespace
metadata:
  name: openshift-insights
  annotations:
    openshift.io/node-selector: ""
  labels:
    openshift.io/cluster-monitoring: "true"
    name: openshift-insights
