kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cluster-samples-operator-proxy-reader
subjects:
  - kind: ServiceAccount
    name: cluster-samples-operator
    namespace: openshift-cluster-samples-operator
roleRef:
  kind: ClusterRole
  name: cluster-samples-operator-proxy-reader
