apiVersion: v1
kind: ConfigMap
metadata:
  namespace: openshift-insights
  name: service-ca-bundle
  annotations:
    release.openshift.io/create-only: "true"
    service.beta.openshift.io/inject-cabundle: "true"
