apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: openshift-apiserver-operator
  name: openshift-apiserver-operator
  labels:
    app: openshift-apiserver-operator
  annotations:
    exclude.release.openshift.io/internal-openshift-hosted: "true"
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: openshift-apiserver-operator
  template:
    metadata:
      name: openshift-apiserver-operator
      labels:
        app: openshift-apiserver-operator
    spec:
      serviceAccountName: openshift-apiserver-operator
      containers:
      - name: openshift-apiserver-operator
        terminationMessagePolicy: FallbackToLogsOnError
        image: quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:080bd406170b1df58f48e416702fd11d3efa5010a26e901056635fcd1016cc59
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8443
          name: metrics
          protocol: TCP
        command: ["cluster-openshift-apiserver-operator", "operator"]
        args:
        - "--config=/var/run/configmaps/config/config.yaml"
        resources:
          requests:
            memory: 50Mi
            cpu: 10m
        volumeMounts:
        - mountPath: /var/run/configmaps/config
          name: config
        - mountPath: /var/run/secrets/serving-cert
          name: serving-cert
        env:
        - name: IMAGE
          value: quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:4aeb222edaf338f9acc42521e5a16e76a6f305f121b2bccafc4ed9e167efcb95
        - name: OPERATOR_IMAGE
          value: quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:080bd406170b1df58f48e416702fd11d3efa5010a26e901056635fcd1016cc59
        - name: OPERATOR_IMAGE_VERSION
          value: "4.5.4"
        - name: OPERAND_IMAGE_VERSION
          value: "4.5.4"
      volumes:
      - name: serving-cert
        secret:
          secretName: openshift-apiserver-operator-serving-cert
          optional: true
      - name: config
        configMap:
          name: openshift-apiserver-operator-config
      nodeSelector:
        node-role.kubernetes.io/master: ""
      priorityClassName: "system-cluster-critical"
      tolerations:
      - key: "node-role.kubernetes.io/master"
        operator: "Exists"
        effect: "NoSchedule"
      - key: "node.kubernetes.io/unreachable"
        operator: "Exists"
        effect: "NoExecute"
        tolerationSeconds: 120
      - key: "node.kubernetes.io/not-ready"
        operator: "Exists"
        effect: "NoExecute"
        tolerationSeconds: 120
