apiVersion: v1
kind: Service
metadata:
  name: machine-config-daemon
  namespace: openshift-machine-config-operator
  labels:
    k8s-app: machine-config-daemon
  annotations:
    service.beta.openshift.io/serving-cert-secret-name: proxy-tls
spec:
  type: ClusterIP
  selector:
    k8s-app: machine-config-daemon
  ports:
  - name: metrics
    port: 9001
    protocol: TCP
