apiVersion: config.openshift.io/v1
kind: ClusterOperator
metadata:
  name: machine-config
  annotations:
    exclude.release.openshift.io/internal-openshift-hosted: "true"
spec: {}
status:
  versions:
    - name: operator
      version: "4.5.4"
  relatedObjects:
    - group: ""
      name: openshift-machine-config-operator
      resource: namespaces
    - group: machineconfiguration.openshift.io
      name: master
      resource: machineconfigpools
    - group: machineconfiguration.openshift.io
      name: worker
      resource: machineconfigpools
    - group: machineconfiguration.openshift.io
      name: machine-config-controller
      resource: controllerconfigs
