apiVersion: v1
kind: ConfigMap
metadata:
  namespace: openshift-cluster-storage-operator
  name: csi-snapshot-controller-operator-config
  labels:
    app: csi-snapshot-controller-operator
data:
  operator-config.yaml: |
    apiVersion: operator.openshift.io/v1alpha1
    kind: GenericOperatorConfig
