# Role for the operator itself.
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ingress-operator
  namespace: openshift-ingress-operator
rules:
- apiGroups:
  - operator.openshift.io
  resources:
  - "*"
  verbs:
  - "*"

- apiGroups:
  - ""
  resources:
  - pods
  - services
  - endpoints
  - persistentvolumeclaims
  - events
  - configmaps
  - secrets
  verbs:
  - "*"

- apiGroups:
  - apps
  resources:
  - deployments
  - services
  verbs:
  - "*"
