kind: Namespace
apiVersion: v1
metadata:
  annotations:
    openshift.io/node-selector: ""
  labels:
    # allow openshift-monitoring to look for ServiceMonitor objects in this namespace
    openshift.io/cluster-monitoring: "true"
  name: openshift-ingress-operator
