apiVersion: batch/v1
kind: Job
metadata:
  name: openshift-service-catalog-controller-manager-remover
  namespace: openshift-service-catalog-removed
  annotations:
    release.openshift.io/create-only: "true"
spec:
  template:
    spec:
      serviceAccountName: openshift-service-catalog-controller-manager-remover
      containers:
      - name: openshift-service-catalog-controller-manager-remover
        securityContext: {}
        # image will be some registry image
        image: quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:da22234daa2aa1640e2a2c31d9c1962ddb77822cea26b38bf75d34409502d7f1
        command: ["/usr/bin/cluster-svcat-controller-manager-remover"]
        resources:
          requests:
            memory: 50Mi
      restartPolicy: Never
  backoffLimit: 4
