apiVersion: v1
kind: Service
metadata:
  name: marketplace-operator-metrics
  namespace: openshift-marketplace
  annotations:
    service.alpha.openshift.io/serving-cert-secret-name: marketplace-operator-metrics
  labels:
    name: marketplace-operator
spec:
  selector:
    name: marketplace-operator
  ports:
  - name: metrics
    port: 8383
    protocol: TCP
    targetPort: 8383
  - name: https-metrics
    port: 8081
    protocol: TCP
    targetPort: 8081
