kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cluster-storage-operator
subjects:
- kind: ServiceAccount
  name: cluster-storage-operator
  namespace: openshift-cluster-storage-operator
roleRef:
  kind: ClusterRole
  name: cluster-storage-operator
  apiGroup: rbac.authorization.k8s.io
