apiVersion: console.openshift.io/v1
kind: ConsoleLink
metadata:
  name: openshift-learning-portal
spec:
  href: 'https://learn.openshift.com/?ref=webconsole'
  location: HelpMenu
  text: Learning Portal