---
apiVersion: v1
kind: Namespace
metadata:
  name: openshift-image-registry
  annotations:
    openshift.io/node-selector: ""
  labels:
    openshift.io/cluster-monitoring: "true"
spec:
  finalizers:
  - kubernetes
