# Configure cluster-monitoring for cluster-authentication-operator
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: authentication-operator
  namespace: openshift-authentication-operator
spec:
  endpoints:
  - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
    interval: 30s
    metricRelabelings:
    - action: drop
      regex: etcd_(debugging|disk|request|server).*
      sourceLabels:
      - __name__
    path: /metrics
    port: https
    scheme: https
    tlsConfig:
      caFile: /etc/prometheus/configmaps/serving-certs-ca-bundle/service-ca.crt
      serverName: metrics.openshift-authentication-operator.svc
  jobLabel: component
  selector:
    matchLabels:
      app: authentication-operator
---
# Configure cluster-monitoring for cluster authentication resources
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: oauth-openshift
  namespace: openshift-authentication
spec:
  endpoints:
  - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
    interval: 30s
    metricRelabelings:
    - action: drop
      regex: etcd_(debugging|disk|request|server).*
      sourceLabels:
      - __name__
    path: /metrics
    port: https
    scheme: https
    tlsConfig:
      caFile: /etc/prometheus/configmaps/serving-certs-ca-bundle/service-ca.crt
      serverName: oauth-openshift.openshift-authentication.svc
  jobLabel: component
  selector:
    matchLabels:
      app: oauth-openshift
