---
apiVersion: v1
kind: Service
metadata:
  name: machine-api-operator
  namespace: openshift-machine-api
  annotations:
    service.alpha.openshift.io/serving-cert-secret-name: machine-api-operator-tls
    exclude.release.openshift.io/internal-openshift-hosted: "true"
  labels:
    k8s-app: machine-api-operator
spec:
  type: ClusterIP
  ports:
  - name: https
    port: 8443
    targetPort: https
  selector:
    k8s-app: machine-api-operator
  sessionAffinity: None
