apiVersion: v1
kind: LimitRange
metadata:
  name: project-limitrange
spec:
  limits:
  - default:
      memory: 100Mi
      cpu: 100m
    defaultRequest:
      memory: 30Mi
      cpu: 30m
    type: Container
